name: Deploy to yoshiko.net

on:
  push:

env:
  ssh_key_path: ~/.ssh/yoshikouki.net.pem
  github_key_path: ~/.ssh/id_rsa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm build
      - run: jest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate SSH key for AWS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACCESS_KEY_TO_AWS }}" > ${{ env.ssh_key_path }}
          chmod 400 ${{ env.ssh_key_path }}
          eval "$(ssh-agent -s)"
          ssh-add ${{ env.ssh_key_path }}
      - name: Generate SSH key for GitHub
        run: |
          ssh -i ${{ env.ssh_key_path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          'find ${{ env.github_key_path }} > /dev/null \
          || (cd ~/.ssh \
          && sudo echo "${{ secrets.ACCESS_KEY_TO_GITHUB }}" > ${{ env.github_key_path }} \
          && sudo chmod 400 ${{ env.github_key_path }})'
      - name: Deploy and Build with PM2
        run: |
          which pm2 > /dev/null || (echo "Install PM2"; sudo npm install -g pm2)
          pm2 deploy ecosystem.config.js production
